[package]
name = "foo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type=["cdylib"]

[dependencies]
node-bindgen-min = { path = "../" }

[build-dependencies]
node-bindgen-min = { path = "../", default-features=false, features=["build"] }
